version: 2

mergeable:
  - when: pull_request.*
    name: "Description check"

    filter: # to ignore Feedback branch
      - do: payload
        pull_request:
          title:
            must_exclude:
              regex: ^Feedback$
              regex_flag: none

    validate:
      - do: description
        no_empty:
          enabled: true
          message: Description should not be empty! Please provide a description for this pull request.

  - when: pull_request.*, pull_request_review.*
    name: 'Approval check'

    filter: # to ignore Feedback branch
      - do: payload
        pull_request:
          title:
            must_exclude:
              regex: ^Feedback$
              regex_flag: none

    validate:
      - do: approvals
        min:
          count: 2
        block:
          changes_requested: true
        required:
          requested_reviewers: true
          message: All requested reviewers must approve changes before merging.
        limit:
          users: [ 'VersusXX', 'AlexandrKudrya', '7gambit7' ]